apiVersion: v1
kind: Secret
metadata:
  name: oci-registry
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: ghcr.io/myorg
  name: github-container-registry
  enableOCI: "true"
  username: github-username
  password: ghcr-token