apiVersion: v1
kind: Secret
metadata:
  name: helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://charts.bitnami.com/bitnami
  name: bitnami
  
  # For authenticated Helm repos
  username: my-username
  password: my-password
  
  # For OCI-based Helm charts
  enableOCI: "true"
  
  # Project scope
  project: my-project